### ISSUE TITLE
🛠 Suggest support expected values produced by function parameter

### ISSUE THREAD

**Issue by lisadhl** [openreachtech/jest-expect-each#35]
## Overview

* When I have an array of actual values to assert all greater than a specified value, now I have to write the following codes:

```js
    const minimums = Array(flattedRawHttpStatusCodes.length).fill(100)
    const maximums = Array(flattedRawHttpStatusCodes.length).fill(600)

    // @ts-expect-error
    expect.each(allCodes).toBeGreaterThanOrEqual(minimums)

    // @ts-expect-error
    expect.each(allCodes).toBeLessThan(maximums)
```

If the tool support the function parameter to provide the expected value, I will feel more happy:

```js
    // @ts-expect-error
    expect.each(allCodes).toBeGreaterThanOrEqual((actualValue, index) => 100)
```

## Tasks

- [ ]

**Comment by StewEucen** [comment]
@lisadhl 

* Thank you for your opinion :)

## Two points

1. I have already known that the code to create an array with the same values is not cool.
  > 同じ値の配列を作るコードがスマートではないことは既に把握しています。
2. Specifications that are counter-intuitive should be considered last and not first proposed. 
  > 直感に反する仕様は最後に検討されるべきであり、最初に提案されるべきではない。

## Policy

* `expect.each()` requests array parameter to matcher methods. The spec is simplest now.
  > `expect.each()` は matcher のメソッドに配列のパラメータを要求します。この仕様が一番シンプルです。
  
* It is best to have only one specification, and to be cautious about increasing one to two. Lisa's proposed specification is complex and should not be forced on users of `expect.each()`.
  > 仕様はひとつだけ存在するのがベストで、ひとつをふたつに増やすのは慎重であるべきです。Lisa さんが提案した仕様は複雑で、`expect.each()` の使用者に強いるべきではないでしょう。
  
## Considerations

### 1. Change in-house ESLint policy

* Discard `expect.each()` and allow Array#forEach() only in describe().
  > ORT のコーディングルールから `expect.each()` を捨てて、 describe() 内のみ Array#forEach() を許可する。
  
* This approach can lead to test cases being vandalized by less skilled developers and should be avoided if possible.
  > 此の方法では、技量の低い開発者によってテストケースが荒らされる恐れがあり、可能であれば避けたいです。

### 2. Does not use `expect.each()` to array with all same values

* We can replace it with other expect statement easily.
  > 他の expect 文に簡単に置き換えることができます。

* If the test target method is not async function, does not require `expect.each()`.
  > テスト対象のメソッドが非同期関数でない場合、 `expect.each()` は不要です。
    ```
    describe('SampleClass', () => {
      const sample = SampleClass.create()
      const received = sample.getValues()

      test.each(received)('value: %s', (value) => {
        expect(value).toBe(600)
      })
    })
    ```

* If the test target method is async function, It can be written as follows without `expect.each()`.
    
    ```
    describe('SampleClass', () => {
      test.each(received)('value: %s', async (value) => {
        const sample = SampleClass.create()
        const received = await sample.getValues()

        expect(new Set(received).size).toBe(1)
        expect(received).toEqual(expect.arrayContaining(600))
      })
    })
    ```

**Comment by lisadhl** [comment]
@StewEucen 

Thank you very much! Indeed `test.each` can resolve my problem.
